//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPractice.DBConnection
{
    using System;
    using System.Collections.Generic;
    
    public partial class BMI
    {
        public int BMI_ID { get; set; }
        public string NameBMI { get; set; }
        public string LogoBMI { get; set; }
    }
}
