//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPractice.DBConnection
{
    using System;
    using System.Collections.Generic;
    
    public partial class KitItem
    {
        public int KitItemId { get; set; }
        public string RaceKitOptionId { get; set; }
        public int InventoryItemId { get; set; }
        public int Quantity { get; set; }
    
        public virtual InventoryItem InventoryItem { get; set; }
        public virtual RaceKitOption RaceKitOption { get; set; }
    }
}
